# Generated by Django 4.2.1 on 2023-05-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="short_desc",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
